# Generated by Django 5.0 on 2025-09-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_signature'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signature',
            unique_together=set(),
        ),
    ]
